#!/usr/bin/env bash
set -euo pipefail

# Simple, reproducible environment setup for Veil
#
# Usage:
#   bash scripts/setup_env.sh [--cpu|--gpu]
#
# Notes:
# - Uses the currently active Python environment. To use a specific env,
#   activate it before running this script (e.g., mamba/conda env or venv).
# - Installs CUDA-enabled torch when --gpu is passed or when an NVIDIA GPU is detected.

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$REPO_ROOT"

PYTHON_BIN=${PYTHON_BIN:-python3}
PIP_BIN="$PYTHON_BIN -m pip"

want_gpu="auto"
if [[ "${1:-}" == "--cpu" ]]; then
  want_gpu="no"
elif [[ "${1:-}" == "--gpu" ]]; then
  want_gpu="yes"
fi

echo "[setup] Using Python: $($PYTHON_BIN -c 'import sys; print(sys.executable)')"
echo "[setup] Python version: $($PYTHON_BIN -c 'import sys; print(sys.version)')"

echo "[setup] Installing base repo requirements..."
$PIP_BIN install --upgrade pip setuptools wheel

echo "[setup] Installing uv..."
$PIP_BIN install uv
PIP_BIN="$PYTHON_BIN -m uv pip"

$PIP_BIN install -r requirements.txt

# Decide CPU vs GPU torch
install_gpu_torch=false
if [[ "$want_gpu" == "yes" ]]; then
  install_gpu_torch=true
elif [[ "$want_gpu" == "auto" ]]; then
  if command -v nvidia-smi >/dev/null 2>&1; then
    install_gpu_torch=true
  fi
fi

if $install_gpu_torch; then
  echo "[setup] Installing CUDA-enabled PyTorch (CUDA 12.6 channel with PyPI fallback)..."
  $PIP_BIN install --no-cache-dir --upgrade \
    --index-url https://download.pytorch.org/whl/cu126 \
    --extra-index-url https://pypi.org/simple \
    torch==2.7.1
else
  echo "[setup] Installing CPU-only PyTorch (with PyPI fallback)..."
  $PIP_BIN install --no-cache-dir --upgrade \
    --index-url https://download.pytorch.org/whl/cpu \
    --extra-index-url https://pypi.org/simple \
    torch
fi

# Transformers do not require torchvision/torchaudio; avoid conflicts
echo "[setup] Ensuring no torchvision/torchaudio conflicts..."
$PIP_BIN uninstall -y torchvision torchaudio >/dev/null 2>&1 || true

echo "[setup] Configuring global git identity..."
if command -v git >/dev/null 2>&1; then
  git config --global user.email "jemanac1998@gmail.com"
  git config --global user.name "chus-chus"
else
  echo "[setup] git not found; skipping global git config" >&2
fi

echo "[setup] Installing mamba/conda activation hooks (PYTHONPATH auto-export)..."
ACTIVATE_DIR="$REPO_ROOT/env/etc/conda/activate.d"
DEACTIVATE_DIR="$REPO_ROOT/env/etc/conda/deactivate.d"
mkdir -p "$ACTIVATE_DIR" "$DEACTIVATE_DIR"

# Ensure PYTHONPATH is automatically set whenever the env is activated
cat > "$ACTIVATE_DIR/veil.sh" <<EOF
# Veil repo activation hook (auto-generated by scripts/setup_env.sh)
export _VEIL_OLD_PYTHONPATH="${PYTHONPATH:-}"
export VEIL_REPO_ROOT="$REPO_ROOT"
export PYTHONPATH="$REPO_ROOT:${PYTHONPATH:-}"
EOF

# Restore PYTHONPATH on environment deactivation
cat > "$DEACTIVATE_DIR/veil.sh" <<'EOF'
# Veil repo deactivation hook (auto-generated by scripts/setup_env.sh)
if [ -n "${_VEIL_OLD_PYTHONPATH+x}" ]; then
  export PYTHONPATH="${_VEIL_OLD_PYTHONPATH}"
  unset _VEIL_OLD_PYTHONPATH
fi
unset VEIL_REPO_ROOT
EOF

echo "[setup] -> activating repository via scripts/activate_repo.sh"
set --
source "$REPO_ROOT/scripts/activate_repo.sh"